name: Update wiki

on:
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          ref: master

      - run: find .

      - run: |
          curl -L $HREF -o bucket_boy.png
          cat << EOF > Home.md
          ![bucket_boy](./bucket_boy.png)
          EOF
          git add .
          git commit -mUpdate
          git push
        env:
          HREF: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi_KDuCUJ4SXPSs6ZVz2LFbkWyS4XTccFEfiizRuoUPM9PmR1Ob9P7IJpFG4hb2_wloVK6eMLvN8bwv8ILauUQWacxn7DzeHCvuQudsNZucMUTrzaMdHRzwjBJ5pDVJNTMhwAnDegyKBtAs6wEjFgsc2HY-9q4WoCHVuBzYIQ_Xv1KPBK8ZBHyx9EpGX3PA/s400/bucket_boy.png"
