name: Update wiki

on:
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          ref: master
          path: .wiki

      - run: find .
